name: Slack notification when approved

on:
  pull_request_review:
    types: [submitted]

jobs:
  notification-changes-requested-to-6161990:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == '6161990'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U04M3J6AHAS>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }

  notification-changes-requested-to-JeremyShin:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == 'JeremyShin'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U055KQ0C9EJ>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }

  notification-changes-requested-to-JiwonDev:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == 'JiwonDev'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U03EVALAKHB>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }

  notification-changes-requested-to-Junuu:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == 'Junuu'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U0446HGG3TK>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }

  notification-changes-requested-to-khcho902:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == 'khcho902'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U03HTSNCV09>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }

  notification-changes-requested-to-kji6252:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == 'kji6252'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U03RJL2EH7G>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }

  notification-changes-requested-to-moon9ua:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == 'moon9ua'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U03HF83L742>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }

  notification-changes-requested-to-pado0:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == 'pado0'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U033L0WCKE1>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }

  notification-changes-requested-to-yeoonjae:
    if: github.event.review.state == 'approved' && github.event.pull_request.user.login == 'yeoonjae'
    runs-on: ubuntu-latest
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "channel": "#ì½”í‹€ë¦°-ë¯¸ì…˜-ìŠ¤í„°ë””",
              "username": "ì‚¬ì´ë³´ê·¸ í˜„êµ¬ë§‰",
              "text": "<@U03EHKUTDD5>ë‹˜, ë¦¬ë·°ì–´ê°€ PRì„ Approve í–ˆìŠµë‹ˆë‹¤! ğŸ‰\në¦¬ë·°ì–´ì˜ ì½”ë©˜íŠ¸ë¥¼ í™•ì¸í•˜ê³  ë‹¤ìŒ ë‹¨ê³„ë¥¼ ì§„í–‰í•´ì£¼ì„¸ìš”.\nhttps://github.com/mission-study-to-finish-in-15-days/kotlin-racingcar/pull/${{ github.event.pull_request.number }}",
              "icon_url": "https://opgg-static.akamaized.net/meta/images/lol/champion/Blitzcrank.png?image=c_crop,h_103,w_103,x_9,y_9/q_auto,f_webp,w_160&v=1690894796332"
            }
